// Remove this comment after installing DOTween via Asset Store
#define DOTWEEN

using UnityEngine;
#if DOTWEEN
using DG.Tweening;
#endif

namespace HexWords.UI.Transitions
{
    /// <summary>
    /// ScriptableObject that defines how hex cells animate in/out as a wave.
    /// Assign to <see cref="CellGridAnimator"/>.
    /// </summary>
    [CreateAssetMenu(menuName = "HexWords/UI/Cell Grid Transition Config", fileName = "CellGridTransitionConfig")]
    public class CellGridTransitionConfig : ScriptableObject
    {
        [Header("Wave Shape")]
        [Tooltip("Determines the order cells animate in.")]
        public WaveOrigin waveOrigin = WaveOrigin.TopToBottom;

        [Tooltip("Angle in degrees for DirectionalAngle mode (0 = right, 90 = up, 270 = down).")]
        [Range(0f, 360f)]
        public float customAngle = 270f;

        [Tooltip("If true, the disappear wave runs in the reverse order of the appear wave.")]
        public bool mirrorOriginForDisappear = true;

        [Header("Timing")]
        [Tooltip("Delay between successive cells in the wave (seconds).")]
        public float cellStagger = 0.045f;

        [Tooltip("Max random jitter added to each cell's stagger delay (± jitter/2 seconds).")]
        public float cellStaggerRandomJitter = 0.01f;

        [Header("Appear Config  (applied to each cell)")]
        public TransitionElementConfig cellAppearConfig = new TransitionElementConfig
        {
            duration       = 0.30f,
            alphaEnabled   = true,
            alphaFrom      = 0f,
            alphaTo        = 1f,
            scaleEnabled   = true,
            scaleFrom      = new Vector3(0.6f, 0.6f, 1f),
            scaleTo        = Vector3.one,
#if DOTWEEN
            // Ease values set below via Reset(); Unity won't serialize conditional fields cleanly,
            // so we use field initializers that reference the same defaults as TransitionElementConfig.
#endif
        };

        [Header("Disappear Config  (leave empty to mirror appear)")]
        [Tooltip("If all properties are disabled, disappear is auto-generated by mirroring appear config.")]
        public TransitionElementConfig cellDisappearConfig = new TransitionElementConfig
        {
            duration       = 0.22f,
            alphaEnabled   = true,
            alphaFrom      = 1f,
            alphaTo        = 0f,
            scaleEnabled   = true,
            scaleFrom      = Vector3.one,
            scaleTo        = new Vector3(0.6f, 0.6f, 1f),
        };

        // ── Runtime helper ─────────────────────────────────────────────────

        /// <summary>
        /// Returns the effective disappear config: either <see cref="cellDisappearConfig"/>
        /// if any property is enabled, or a mirrored copy of <see cref="cellAppearConfig"/>.
        /// </summary>
        public TransitionElementConfig GetDisappearConfig()
        {
            var d = cellDisappearConfig;
            bool hasAny = d.alphaEnabled || d.scaleEnabled || d.positionEnabled || d.rotationEnabled;
            return hasAny ? d : cellAppearConfig.Mirrored();
        }
    }
}
